apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lora-connector.fullname" . }}
  labels:
    {{- include "lora-connector.labels" . | nindent 4 }}
type: Opaque
data: 
  key: {{ .Values.publicKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lora-connector.fullname" . }}-mysql
  labels:
    {{- include "lora-connector.labels" . | nindent 4 }}
type: Opaque
data: 
  username: {{ .Values.mysql.username }}
  password: {{ .Values.mysql.password }}
