# Default values for lora-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: eu.gcr.io/molten-mariner-162315/connctd/lora-connector
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations:
  sqlbee.connctd.io.inject: "true"

podSecurityContext: {}
  # fsGroup: 
  
mysql:
  db: chirpstack_connector
  username: chirpstack_connector

securityContext:
  capabilities:
     drop:
     - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
  - host: chirpstack.lora.connctd.io
    paths:
      - path: /lorawan
        pathType: ImplementationSpecific
      - path: /connector
        pathType: ImplementationSpecific
  tls:
  - secretName: chirpstack.lora.connctd.io
    hosts:
    - chirpstack.lora.connctd.io

resources: 
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
